### ISSUE TITLE
Cache error

### ISSUE THREAD

**Issue by camjac251** [TheReverend403/uPste#19]
I'm not sure if this was a one time thing or a bug but I think the cache failed to load this one time for 1 client. I uploaded a file to give to them and opened it myself and it worked just fine, but when they opened it up, I started receiving "Application Exception" emails
`ErrorException: file_put_contents(/path/to/upste/storage/framework/cache/ee/1e/40characterrandomcodehere): failed to open stream: No such file or directory in /path/to/upste/bootstrap/cache/compiled.php:7366`

```
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'file_put_conten...', '/path/t...', 7366, Array)
#1 /path/to/upste/bootstrap/cache/compiled.php(7366): file_put_contents('/path/t...', '1469354863i:1;', 2)
#2 /path/to/upste/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(106): Illuminate\Filesystem\Filesystem->put('/path/t...', '1469354863i:1;', true)
#3 /path/to/upste/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(206): Illuminate\Cache\FileStore->put('cached_view:173...', '1469354863i:1;', 60)
#4 [internal function]: Illuminate\Cache\Repository->put('cached_view:173...', 1, 60)
#5 /path/to/upste/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php(296): call_user_func_array(Array, Array)
#6 /path/to/upste/bootstrap/cache/compiled.php(6329): Illuminate\Cache\CacheManager->__call('put', Array)
#7 /path/to/upste/app/Http/Controllers/DownloadController.php(28): Illuminate\Support\Facades\Facade::__callStatic('put', Array)
#8 [internal function]: App\Http\Controllers\DownloadController->get(Object(Illuminate\Http\Request), Object(App\Models\Upload))
#9 /path/to/upste/bootstrap/cache/compiled.php(9419): call_user_func_array(Array, Array)
#10 /path/to/upste/bootstrap/cache/compiled.php(9481): Illuminate\Routing\Controller->callAction('get', Array)
#11 /path/to/upste/bootstrap/cache/compiled.php(9461): Illuminate\Routing\ControllerDispatcher->call(Object(App\Http\Controllers\DownloadController), Object(Illuminate\Routing\Route), 'get')
#12 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#13 /path/to/upste/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#14 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#15 /path/to/upste/bootstrap/cache/compiled.php(9938): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#16 /path/to/upste/bootstrap/cache/compiled.php(9462): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#17 /path/to/upste/bootstrap/cache/compiled.php(9449): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(App\Http\Controllers\DownloadController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'get')
#18 /path/to/upste/bootstrap/cache/compiled.php(8517): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'App\\Http\\Contro...', 'get')
#19 /path/to/upste/bootstrap/cache/compiled.php(8504): Illuminate\Routing\Route->runController(Object(Illuminate\Http\Request))
#20 /path/to/upste/bootstrap/cache/compiled.php(8218): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#21 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#22 /path/to/upste/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#23 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#24 /path/to/upste/bootstrap/cache/compiled.php(9938): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#25 /path/to/upste/bootstrap/cache/compiled.php(8219): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#26 /path/to/upste/bootstrap/cache/compiled.php(8210): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#27 /path/to/upste/bootstrap/cache/compiled.php(8200): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#28 /path/to/upste/bootstrap/cache/compiled.php(2419): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#29 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#30 /path/to/upste/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#31 /path/to/upste/bootstrap/cache/compiled.php(3225): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#32 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#33 /path/to/upste/bootstrap/cache/compiled.php(9953): call_user_func_array(Array, Array)
#34 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#35 /path/to/upste/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#36 /path/to/upste/bootstrap/cache/compiled.php(13400): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#37 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#38 /path/to/upste/bootstrap/cache/compiled.php(9953): call_user_func_array(Array, Array)
#39 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 /path/to/upste/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#41 /path/to/upste/bootstrap/cache/compiled.php(11943): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#42 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#43 /path/to/upste/bootstrap/cache/compiled.php(9953): call_user_func_array(Array, Array)
#44 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#45 /path/to/upste/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#46 /path/to/upste/bootstrap/cache/compiled.php(13139): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#47 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#48 /path/to/upste/bootstrap/cache/compiled.php(9953): call_user_func_array(Array, Array)
#49 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#50 /path/to/upste/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#51 /path/to/upste/bootstrap/cache/compiled.php(13076): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#52 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#53 /path/to/upste/bootstrap/cache/compiled.php(9953): call_user_func_array(Array, Array)
#54 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#55 /path/to/upste/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#56 /path/to/upste/bootstrap/cache/compiled.php(3286): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#57 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#58 /path/to/upste/bootstrap/cache/compiled.php(9953): call_user_func_array(Array, Array)
#59 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#60 /path/to/upste/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#61 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#62 /path/to/upste/bootstrap/cache/compiled.php(9938): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#63 /path/to/upste/bootstrap/cache/compiled.php(2366): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#64 /path/to/upste/bootstrap/cache/compiled.php(2350): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#65 /path/to/upste/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#66 {main}
```

**Comment by lwatsondev** [comment]
Looks to me like it's a bug in the underlying cache driver, or there's something going wrong with your filesystem. All my testing is done with the file cache driver, and I haven't had a single problem like this with any cache method.

**Comment by lwatsondev** [comment]
Closing due to no reply.
